#!/bin/sh
#
# 2013 Daniel Heule (hda at sfs.biz)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the ID of the zypper service configured to use --uri.
#

if [ -f "${__object:?}/parameter/uri" ]
then
   uri=$(cat "${__object:?}/parameter/uri")
else
   uri="/${__object_id:?}"
fi
# simpler command which works only on SLES11 SP3 or newer:
# echo $(zypper ls -u -E | grep -E "\<${uri}\>" | cut -d'|' -f 1 )
#
# shellcheck disable=SC2005,SC2046
echo $(zypper ls -u | grep -E '^([^|]+\|){3,3} Yes' | grep -E "\\<${uri}\\>" | cut -d'|' -f 1)
