#!/bin/sh -e
#
# 2021 Ander Punnar (ander at kvlt.ee)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Print the contents of the desination file or raise an error if it does not
# exist.
#

if [ -f "${__object:?}/parameter/file" ]
then
    file=$(cat "${__object:?}/parameter/file")
else
    file="/${__object_id:?}"
fi

test -r "${file}" || {
    echo "${file} does not exist (or is not readable)" >&2
    exit 1
}

cat "${file}"
