#!/bin/sh -e
#
# 2024 Ander Punnar (ander-at-kvlt-dot-ee)
# 2024 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.

found="$__object/explorer/find"

if [ ! -s "$found" ]
then
    exit 0
fi

echo '${__type:?}/explorer/find -depth -exec rm -rf {} +'

ln -sf "$found" "$__messages_out"

onchange="$__object/parameter/onchange"

if [ -f "$onchange" ]
then
    cat "$onchange"
fi
