#!/bin/sh -e
#
# 2022 Dennis Camera (cdist at dtnr.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the assembled requirement that can be passed to pip for installation.
#
# This explorer can be removed when the deprecated --name and --extra parameters
# are removed.
#

comma_join() { sed ':a; $!N; s/\n/,/; ta'; }

if test -f "${__object:?}/parameter/requirement"
then
	requirement=$(cat "${__object:?}/parameter/requirement")
else
	if test -f "${__object:?}/parameter/name"  # deprecated
	then
		requirement=$(cat "${__object:?}/parameter/name")
	else
		requirement=${__object_id:?}
	fi

	if test -s "${__object:?}/parameter/extra"  # deprecated
	then
		extras=$(comma_join <"${__object:?}/parameter/extra")
		requirement="${requirement}[${extras}]"
	fi
fi

printf '%s\n' "${requirement}"
