#!/bin/sh
#
# 2013 Steven Armstrong (steven-cdist armstrong.cc)
# 2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

os=$("$__explorer/os")

destination="/$__object_id"

passwd_lookup() {
   # usage: passwd_lookup file needle match_col print_col
   awk -F ':' -v needle="${2:?}" -v mcol=$((${3:?})) -v pcol=$((${4:?})) '
   $mcol == needle {
      print $pcol
      f = 1
   }
   END {
      if (!f)
         print "UNKNOWN"
   }' "${1:?}"
}

fallback() {
   # Patch the output together, manually

   if test "${os}" != 'sortix'
   then
      read -r mode_text links uid gid size _ <<EOF
$(ls -ldn "${destination}")
EOF

      owner=$(passwd_lookup /etc/passwd $((uid)) 3 1)
      group=$(passwd_lookup /etc/group $((gid)) 3 1)
   else
      # NOTE: Sortix' ls(1) does not currently support the -n option
      read -r mode_text links owner group size _ <<EOF
$(ls -ld "${destination}")
EOF

      uid=$(passwd_lookup /etc/passwd "${owner}" 1 3)
      gid=$(passwd_lookup /etc/group "${group}" 1 3)
   fi

   mode=$(echo "${mode_text}" | awk '{for(i=8;i>=0;--i){c=substr($1,10-i,1);k+=((c~/[rwxst]/)*2^i);if(!(i%3))k+=(tolower(c)~/[lst]/)*2^(9+i/3)}printf("%04o",k)}')

   printf 'type: %s\nowner: %d %s\ngroup: %d %s\nmode: %s %s\n' \
      "$("$__type_explorer/type")" \
      "$uid" "$owner" \
      "$gid" "$group" \
      "$mode" "$mode_text"
}

# nothing to work with, nothing we could do
[ -e "$destination" ] || exit 0

command -v stat >/dev/null 2>&1 || {
   fallback
   exit
}

case ${os}
in
   freebsd|netbsd|openbsd|macosx)
      stat -f 'type: %HT
owner: %Du %Su
group: %Dg %Sg
mode: %Mp%03Lp %Sp
' "$destination" | awk '/^type/ { print tolower($0); next } { print }'
      ;;
   sortix)
      # NOTE: currently, Sortix' stat(1) does not allow specifying a
      #       format string.
      fallback
      ;;
   *)
      # NOTE: Do not use --printf here as it is not supported by BusyBox stat.
      # NOTE: BusyBox's stat might not support the "-c" option, in which case
      #       we fall through to the shell fallback.
      stat -c 'type: %F
owner: %u %U
group: %g %G
mode: %04a %A' "$destination" 2>/dev/null || fallback
      ;;
esac
