#!/bin/sh -e
#
# 2018 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

name=${__object_id:?}
destination="/etc/apt/sources.list.d/${name}.list"

# Allow release info changes to prevent apt-get(8) aborts e.g. if APT wasn't
# updated between 2021-04-19 and the bullseye release.
# The additional arguments acknowledge the suite change (apt(8) update
# does the same by itself).
#
# Using ’-o’ instead of the --allow-releaseinfo-change-* parameters
# allows backwards compatibility with pre-buster APT versions.
apt_opts='-o Acquire::AllowReleaseInfoChange::Suite=true -o Acquire::AllowReleaseInfoChange::Version=true'

# Run 'apt-get update' only if something changed in our sources.list file
# it will be run a second time on error as a redundancy measure to success.
if grep -q "^__file${destination}" "${__messages_in:?}"
then
	printf 'apt-get %s update || apt-get %s update\n' "${apt_opts}" "${apt_opts}"
fi
