#!/bin/sh -e
#
# 2011-2018 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

name=${__object_id:?}
state=$(cat "${__object:?}/parameter/state")
uri=$(cat "${__object:?}/parameter/uri")

if [ -f "${__object:?}/parameter/distribution" ]; then
   distribution=$(cat "${__object:?}/parameter/distribution")
else
   distribution=$(cat "${__global:?}/explorer/lsb_codename")
fi

component=$(cat "${__object:?}/parameter/component")

if [ -f "${__object:?}/parameter/arch" ]; then
	forcedarch="arch=$(cat "${__object:?}/parameter/arch")"
fi

if [ -f "${__object:?}/parameter/signed-by" ]; then
   # Take all '--signed-by' parameter values present on separate lines and join them with a comma
   signed_by="signed-by=$(sed -e ':a' -e '$!N' -e 's/\n/,/' -e 'ta' "${__object:?}/parameter/signed-by")"
fi

# export variables for use in template
export name
export uri
export distribution
export component
export forcedarch
export signed_by

# generate file from template
mkdir "${__object:?}/files"
"${__type:?}/files/source.list.template" > "${__object:?}/files/source.list"
__file "/etc/apt/sources.list.d/${name}.list" \
   --source "${__object:?}/files/source.list" \
   --owner root --group root --mode 0644 \
   --state "${state}"
