#!/bin/sh -e
#
# 2011 Ramon Salvadó (rsalvado at gnuine.com)
# 2012-2015 Steven Armstrong (steven-cdist at armstrong.cc)
# 2012-2019 Nico Schottelius (nico-cdist at schottelius.org)
# 2020 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

TZ=$(cat "${__object:?}/parameter/tz")
os=$(cat "${__global:?}/explorer/os")
localtime_file=/etc/localtime

case ${os}
in
	(archlinux|alpine|debian|devuan|ubuntu|centos|redhat|scientific)
		__package tzdata
		export require=__package/tzdata
		;;
	(suse)
		__package timezone
		export require=__package/timezone
		;;
	(coreos|freebsd|netbsd|openbsd)
		# whitelist
		;;
	(centos|redhat|scientific)
		__file /etc/sysconfig/clock \
			--state exists \
			--owner 0 --group 0 --mode 0644
		require=__file/etc/sysconfig/clock \
		__key_value /etc/sysconfig/clock:ZONE \
			--file /etc/sysconfig/clock \
			--delimiter '=' --exact_delimiter \
			--key 'ZONE' \
			--value "\"${TZ}\""
		;;
	(*)
		: "${__type:?}"  # make shellcheck happy
		echo "Your operating system (${os}) is currently not supported by this type (${__type##*/})." >&2
		echo 'Please contribute an implementation for it if you can.' >&2
		exit 1
		;;
esac

case ${os}
in
	(ubuntu|debian|devuan|coreos|alpine)
		echo "${timezone_should}" | __file /etc/timezone --source -
		;;
esac

zoneinfo_file="/usr/share/zoneinfo/${TZ}"
__link "${localtime_file}" \
	--type symbolic \
	--source "${zoneinfo_file}"
