#!/bin/sh -e
#
# 2023,2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the sources currently configured for the database.
#

test -f /etc/nsswitch.conf || exit 0

awk -v db_name="${__object_id:?}" '
# prepare line
{
	# remove comments
	sub(/[ \\t]*#.*$/, "")
	# merge line continuations to single line
	while (/\\$/) {
		sub(/\\$/, (0 < (getline _nl) ? _nl : ""))
	}
}

$1 == db_name ":" {
	# store found line, because in nsswitch.conf(5) the last match wins
	line = $0
}

END {
	if (line) {
		$0 = line

		for (i = 2; i <= NF; ++i) {
			printf "%s%s", (i>2 ? " " : ""), $i
		}
		printf ORS
	}
}
' /etc/nsswitch.conf
