#!/bin/sh -e
#
# 2020 Ander Punnar (ander at kvlt.ee)
# 2021 Dennis Camera (skonfig at dtnr.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

# fedora's (update-)alternatives --display output doesn't have
# "link <name> is <path>" line, but debian does. so, let's find
# out how they store this information.
#
# debian and friends:
#   https://salsa.debian.org/dpkg-team/dpkg/-/blob/master/utils/update-alternatives.c
#   see calls to altdb_print_line function
#
# fedora and friends:
#   https://github.com/fedora-sysv/chkconfig/blob/master/alternatives.c
#   see calls to parseLine function
#
# conclusion: it is safe to assume that (master) link is on second line

for altdir in \
    /var/lib/dpkg/alternatives \
    /var/lib/alternatives
do
    if [ ! -f "$altdir/${__object_id:?}" ]
    then
        continue
    fi

    link="$( awk 'NR==2' "$altdir/${__object_id:?}" )"

    if [ -n "$link" ]
    then
        break
    fi
done

if [ -z "$link" ] && [ -z "${__cdist_dry_run+dry run}" ]
then
    # NOTE: ignore error for dry-runs because a package providing the link
    #       might be managed by another cdist object (which wasn't executed,
    #       because dry run…).
    echo "unable to get link for ${__object_id:?}" >&2
    exit 1
fi

echo "$link"
