#!/bin/sh -e
#
# 2020 Ander Punnar (ander at kvlt.ee)
# 2021 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the path currently used for the alternative.
#

path_is=$(
    LC_ALL=C update-alternatives --display "${__object_id?}" 2>/dev/null \
    | awk '/link currently points to/ { print $5 }')

if [ -z "$path_is" ] && [ -z "${__cdist_dry_run+dry run}" ]
then
    # NOTE: ignore error for dry-runs because a package providing the
    #       alternative might be managed by another cdist object (which
    #       wasn't executed, because dry run…).
    echo "unable to get current path for ${__object_id:?}" >&2
    exit 1
fi

echo "$path_is"
