#!/bin/sh -e
#
# 2018 Kamila Součková (kamila at ksp.sk)
# 2018 Jonas Weber (github at jonasw.de)
# 2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

name=${__object_id:?}

state_should=$(cat "${__object:?}/parameter/state")
read -r state_is extra <"${__object:?}/explorer/state" || :

# Short circuit if nothing is to be done
[ "${state_should}" = "${state_is}" ] && exit 0

os=$(cat "${__global:?}/explorer/os")

case ${os}
in
	(freebsd)
		if [ "${state_should}" = 'present' ]
		then
			value='YES'
		else
			value='NO'
		fi
		__key_value "rcconf-${name}-enable" \
			--file /etc/rc.conf \
			--key "${name}_enable" \
			--value "\"${value}\"" \
			--delimiter '='
		;;
	(netbsd)
		rcvar=${extra}
		: "${rcvar:?rcvar detection failed}"
		__key_value "/etc/rc.conf:${rcvar}" \
			--file /etc/rc.conf \
			--delimiter '=' --exact_delimiter \
			--key "${rcvar}" \
			--value "$(
				case ${state_should}
				in
					(present)
						echo YES ;;
					(absent)
						echo NO ;;
				esac)"
		;;
	(*)
		# handled in gencode-remote
		;;
esac
