#!/bin/sh -e
# -*- mode: sh; indent-tabs-mode: t -*-
#
# 2019 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

version_ge() {
	# usage: version_ge version_is min_version_expected
	#
	# compares two version numbers (up to three numeric components separated
	# with dots)
	# returns 0 if `version_is` >= `min_version_expected`, 1 otherwise.
	#
	# NOTES: if the lowest value of the two version numbers is equal to
	#        `min_version_expected`, `version_is` must be the same or larger.
	#        `-k n,n` instead of `-k n` is required for some sort(1)s.
	printf '%s\n' "$1" "$2" \
	| sort -t '.' -n -k 1,1 -k 2,2 -k 3,3 \
	| head -1 \
	| grep -qxF "$2"
}

not_supported() {
	echo "OS ${os} does not support __sensible_editor." >&2
	echo 'If it does, please provide a patch.' >&2
	exit 1
}

os=$(cat "${__global}/explorer/os")
os_version=$(cat "${__global}/explorer/os_version")

state=$(cat "${__object}/parameter/state")
user=$__object_id

if test "${state}" != 'present' && test "${state}" != 'exists' && test "${state}" != 'absent'
then
	echo 'Only "present", "exists", and "absent" are allowed for --state' >&2
	exit 1
fi

package_name='sensible-utils'

case $os
in
	debian)
		pkg_type='apt'
		;;
	devuan)
		pkg_type='apt'
		;;
	ubuntu)
		version_ge "${os_version}" 10.04 || package_name='debianutils'
		pkg_type='apt'
		;;
	centos|fedora|redhat|scientific)
		pkg_type='yum'
		;;
	*)
		not_supported
		;;
esac

if test "${state}" != 'absent'
then
	__package "${package_name}" --state present \
		--type "${pkg_type}"
	export require="__package/${package_name}"
fi

editor_path=$(cat "${__object}/explorer/editor_path")
user_home=$(cat "${__object}/explorer/user_home")
group=$(cat "${__object}/explorer/group")

__file "${user_home}/.selected_editor" --state "${state}" \
	--owner "${user}" --group "${group}" --mode 0644 \
	--source - <<EOF
# Managed by cdist
SELECTED_EDITOR="${editor_path}"
EOF
