#!/bin/sh -e
#
# 2019,2023 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

version_ge() {
	# usage: version_ge version_is min_version_expected
	#
	# compares two version numbers (up to three numeric components separated
	# with dots)
	# returns 0 if `version_is` >= `min_version_expected`, 1 otherwise.
	#
	# NOTES: if the lowest value of the two version numbers is equal to
	#        `min_version_expected`, `version_is` must be the same or larger.
	#        `-k n,n` instead of `-k n` is required for some sort(1)s.
	LC_ALL=C sort -t. -n -k1,1 -k2,2 -k3,3 <<-EOF | { read -r _x; test "${_x}" = "$2"; }
	$1
	$2
	EOF
}

os=$(cat "${__global:?}/explorer/os")

state=$(cat "${__object:?}/parameter/state")
editor_path=$(cat "${__object:?}/explorer/editor_path")
user_home=$(cat "${__object:?}/explorer/user_home")
group=$(cat "${__object:?}/explorer/group")

user=${__object_id:?}

package_name='sensible-utils'

case ${os}
in
	(debian)
		pkg_type='apt'
		;;
	(devuan)
		pkg_type='apt'
		;;
	(ubuntu)
		os_version=$(cat "${__global:?}/explorer/os_version")
		version_ge "${os_version}" 10.04 || package_name='debianutils'
		pkg_type='apt'
		;;
	(centos|fedora|redhat|scientific|oraclelinux)
		pkg_type='yum'
		;;
	(*)
		echo "OS ${os} does not support __sensible_editor." >&2
		echo 'If it does, please provide a patch.' >&2
		exit 1
		;;
esac

case ${state}
in
	(present|exists)
		__package "${package_name}" --state present \
			--type "${pkg_type}"
		export require="__package/${package_name}"
		;;
	(absent)
		;;
	(*)
		printf 'Invalid --state: %s\n' "${state}" >&2
		echo 'Only "present", "exists", and "absent" are allowed for --state' >&2
		exit 1
		;;
esac

__file "${user_home}/.selected_editor" --state "${state}" \
	--owner "${user}" --group "${group}" --mode 0644 \
	--source - <<EOF
# This file is managed by skonfig (__sensible_editor)
# Changes will be overwritten.
SELECTED_EDITOR="${editor_path}"
EOF
