#!/bin/sh -e
#
# 2018 Ander Punnar (ander at kvlt.ee)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the existing ACLs of the destination file.
#
# Raises an error if the getfacl(1) command is not available.
#

[ ! -e "/${__object_id:?}" ] && exit 0

if ! command -v getfacl > /dev/null
then
    echo 'getfacl not available' >&2
    exit 1
fi

getfacl "/${__object_id:?}" 2>/dev/null \
    | grep -Eo '^(default:)?(user|group|(mask|other):):[^:][[:graph:]]+' \
    || :
