#!/bin/sh -e
#
# 2018 Ander Punnar (ander at kvlt.ee)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the current state of the destination file.
#
# One of: directory, regular, other, missing.
#

if [ -e "/$__object_id" ]
then
    if [ -d "/$__object_id" ]
    then echo directory
    elif [ -f "/$__object_id" ]
    then echo regular
    else echo other
    fi
else
    echo missing
fi
