#!/bin/sh -e
#
# 2020 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

TZ=$(cat "${__object:?}/parameter/tz")

case $(uname -s)
in
	(Darwin)
		TZDIR=/var/db/timezone/zoneinfo
		;;
	(SunOS)
		TZDIR=/usr/share/lib/zoneinfo
		;;
	(*)
		# According to glibc's tzfile(5) there are two typical directories:
		if test -d /usr/share/zoneinfo
		then
			# Linux, FreeBSD, OpenBSD, NetBSD. And others?
			TZDIR=/usr/share/zoneinfo
		elif test -d /usr/lib/zoneinfo
		then
			# Old libc4, libc5 apparently.
			TZDIR=/usr/lib/zoneinfo
		else
			exit 0
		fi
esac

if test -e "${TZDIR}/${TZ}"
then
	echo "${TZDIR}/${TZ}"
fi
