#!/bin/sh -e

shquot() {
sed -e "s/'/'\\\\''/g" -e "1s/^/'/" -e "\$s/\$/'/" <<EOF
$*
EOF
}

command -v rsync >/dev/null 2>&1 || {
    echo 'rsync is missing in local machine' >&2
    exit 1
}

src=$(cat "${__object:?}/parameter/source")

test -e "${src}" || {
    echo "${src} not found" >&2
    exit 1
}

if [ -f "${__object:?}/parameter/destination" ]
then
    dst=$(cat "${__object:?}/parameter/destination")
else
    dst="/${__object_id:?}"
fi

# if source is directory, then make sure that
# source and destination are ending with slash,
# because this is what you almost always want when
# rsyncing two directories.

if [ -d "${src}" ]
then
    case ${src}
    in
        (*/)
            ;;
        (*)
            src="${src}/" ;;
    esac

    case ${dst}
    in
        (*/)
            ;;
        (*)
            dst="${dst}/" ;;
    esac
fi

remote_user=$(cat "${__object:?}/parameter/remote-user")

options=$(cat "${__object:?}/parameter/options")

if [ -f "${__object:?}/parameter/option" ]
then
    while read -r l
    do
        # there's a limitation in argparse: value can't begin with '-'.
        # to workaround this, let's prefix opts with '\' in manifest and remove here.
        # read more about argparse issue: https://bugs.python.org/issue9334

        options="${options} ${l#\\}"
    done \
        < "${__object:?}/parameter/option"
fi

if [ -f "${__object:?}/parameter/owner" ] || [ -f "${__object:?}/parameter/group" ]
then
    options="${options} --chown="

    if [ -f "${__object:?}/parameter/owner" ]
    then
        owner=$(cat "${__object:?}/parameter/owner")
        options="${options}$(shquot "${owner}")"
    fi

    if [ -f "${__object:?}/parameter/group" ]
    then
        group=$(cat "${__object:?}/parameter/group")
        options="${options}:$(shquot "${group}")"
    fi
fi

if [ -f "${__object:?}/parameter/mode" ]
then
    mode=$(cat "${__object:?}/parameter/mode")
    options="${options} --chmod=$(shquot "${mode}")"
fi

# IMPORTANT
#
# 1. we first dry-run rsync with change summary to find out
#    if there are any changes and code generation is needed.
# 2. normally, to get current state or target host, we run
#    such operations in type explorers, but that's not
#    possible due to how rsync works.
# 3. redirecting output of dry-run to stderr to ease debugging.
# 4. to understand how that cryptic regex works, please
#    open rsync manpage and read about --itemize-changes.

export RSYNC_RSH="${__remote_exec:?}"

# eval $options into $@ to allow --option to contain quoted shell arguments,
# e.g. for use with rsync's --filter.
eval "set -- ${options}"

# shellcheck disable=SC2086
if ! rsync --dry-run --itemize-changes "$@" "${src}" "${remote_user}@${__target_host:?}:${dst}" \
    | grep -e '^[<>ch.*][fdLDS][cstTpogunbax.+?]\{9\} ' >&2
then
    exit 0
fi

printf 'export RSYNC_RSH=%s\n' "$(shquot "${__remote_exec:?}")"
printf 'rsync%s %s %s@%s:%s\n' \
    "${options:+ ${options# }}" \
    "$(shquot "${src}")" \
    "$(shquot "${remote_user}")" \
    "$(shquot "${__target_host:?}")" \
    "$(shquot "${dst}")"

if [ -f "${__object:?}/parameter/onchange" ]
then
    cat "${__object:?}/parameter/onchange"
fi

echo 'synced' >> "${__messages_out:?}"
