#!/bin/sh -e
#
# 2021-2022 Ander Punnar (ander at kvlt.ee)
# 2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

if [ -f "${__object:?}/parameter/file" ]
then
    file=$(cat "${__object:?}/parameter/file")
else
    file="/${__object_id:?}"
fi

script=$(cat "${__object:?}/parameter/script")

if [ "${script}" = '-' ]
then
    script=$(cat "${__object:?}/stdin")
fi

# since stdin is not available in explorer, we pull file from target with explorer

file_from_target="${__object:?}/explorer/file"

sed_cmd='sed'

if [ -f "${__object:?}/parameter/regexp-extended" ]
then
    sed_cmd="${sed_cmd} -E"
fi

# do sed dry run, diff result and if no change, then there's nothing to do
# also redirect diff's output to stderr for debugging purposes

if echo "${script}" | ${sed_cmd} -f - "${file_from_target}" | diff -u "${file_from_target}" - >&2
then
    exit 0
fi

# we can't use -i, because it's not posix, so we fly with tempfile and cp
# and we use cp because we want to preserve destination file's attributes

# shellcheck disable=SC2016
echo 'tmp="${__object:?}/tempfile"'

echo "${sed_cmd} -f - '${file}' >\"\${tmp}\" <<'EOF'"
echo "${script}"
echo 'EOF'

echo "cp \"\${tmp}\" '${file}'"

# shellcheck disable=SC2016
echo 'rm -f "${tmp}"'

echo 'change' >>"${__messages_out:?}"

if test -s "${__object:?}/parameter/onchange"
then
    cat "${__object:?}/parameter/onchange"
fi
