#!/bin/sh -e
#
# 2020-2021 Ander Punnar (ander at kvlt.ee)
# 2022 Matthias Stecher (matthiasstecher at gmx.de)
# 2023 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

gencode=remote
# shellcheck source=SCRIPTDIR/files/common.sh
. "${__type:?}/files/common.sh"

download=$(cat "${__object:?}/parameter/download")
state_is=$(cat "${__object:?}/explorer/state")

test "${state_is}" != 'present' || exit 0

download_tmp_q=$(shquot "$(remote_download_tmp)")

if test "${download}" = 'remote'
then
	gencode_get "${download_tmp_q}"
fi

# check remote cksum before move to final destination
gencode_cksum "${download_tmp_q}"

# move file to real destination after cksum check
printf 'mv %s %s\n' "${download_tmp_q}" "$(shquot "${remote_dst:?}")"

# execute --onchange (both for local and remote download)
if test -f "${__object:?}/parameter/onchange"
then
	cat "${__object:?}/parameter/onchange"
fi
