#!/bin/sh -e
#
# 2020-2022 Ander Punnar (ander at kvlt.ee)
# 2022 Matthias Stecher (matthiasstecher at gmx.de)
# 2023 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

gencode=local
# shellcheck source=SCRIPTDIR/files/common.sh
. "${__type:?}/files/common.sh"

download=$(cat "${__object:?}/parameter/download")
state_is=$(cat "${__object:?}/explorer/state")

test "${state_is}" != 'present' || exit 0

if test "${download}" = 'local'
then
	# shellcheck disable=SC2016
	echo 'mkdir "${__object:?}/files"'

	# shellcheck disable=SC2016
	local_download_tmp_q='"${__object:?}/files/download_tmp"'
	remote_download_tmp=$(remote_download_tmp)

	gencode_get "${local_download_tmp_q}"

	# check local checksum, will be checked again after transfer to remote
	gencode_cksum "${local_download_tmp_q}"

	if expr "${__target_host:?}" : '[0-9a-fA-F:]\{3,\}$' >/dev/null
	then
		target_host="[${__target_host:?}]"
	else
		target_host=${__target_host:?}
	fi


	# shellcheck disable=SC2016
	printf '%s %s %s <%s\n' \
		"${__remote_exec:?}" \
		"$(shquot "${target_host}")" \
		"$(shquot "cat >$(shquot "${remote_download_tmp:?}")")" \
		"${local_download_tmp_q:?}"

	printf 'rm -f %s\n' "${local_download_tmp_q:?}"
fi
