#!/bin/sh
#
# 2012-2019 Nico Schottelius (nico-cdist at schottelius.org)
# 2013 Daniel Heule (hda at sfs.biz)
# 2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Check whether the given name will be started on boot or not.
#

os=$("${__explorer:?}/os")
runlevel=$("${__explorer:?}/runlevel")
init=$("${__explorer:?}/init")
target_runlevel=$(cat "${__object:?}/parameter/target_runlevel")
name=${__object_id:?}

if [ "${init}" = 'systemd' ]
then
    # this handles ALL linux distros with systemd
    # e.g. archlinux, gentoo, new RHEL and SLES versions
    state=$(systemctl is-enabled "${name}" >/dev/null 2>&1 \
        && echo present \
        || echo absent)

else
    case ${os}
    in
        (debian|openwrt|devuan)
            state='absent'
            for file in "/etc/rc${runlevel}.d/S"??"${name}"
            do
                if [ -f "${file}" ]
                then
                    state='present'
                    break
                fi
            done
            ;;
        (ubuntu)
            state='absent'
            for file in "/etc/rc${runlevel}.d/S"??"${name}"
            do
                if [ -f "${file}" ]
                then
                    state='present'
                    break
                fi
            done

            [ -f "/etc/init/${name}.conf" ] && state='present'
           ;;

        (amazon|scientific|centos|almalinux|eurolinux|rocky|fedora|owl|redhat|oraclelinux)
            if chkconfig --level "${runlevel}" "${name}" >/dev/null 2>&1
            then
                state='present'
            else
                state='absent'
            fi
            ;;
        (suse)
            # check for target if set, usable for boot. services in runlevel B
            if [ "${target_runlevel}" != 'default' ]
            then
                runlevel=${target_runlevel}
            fi
            # suses chkconfig has the same name, but works different ...
            state=$(chkconfig --check "${name}" "${runlevel}" || echo absent)
            test -n "${state}" || state='present'
            ;;
        (gentoo|alpine)
            state='absent'
            for d in /etc/runlevels/*
            do
                if [ -e "${d}/${name}" ]
                then
                    state='present'
                    break
                fi
            done
            ;;
        (freebsd)
            state='absent'
            service -e | grep "/${name}$" && state='present'
            ;;
        (netbsd)
            NL=$(printf '\n.'); NL=${NL%?}

            if test -x /usr/sbin/service
            then
                # NetBSD >= 7.0
                rcvar=$(/usr/sbin/service "${name}" rcvar)
            else
                # NetBSD < 7.0
                rc_script=$(
                    # shellcheck source=/dev/null
                    . /etc/rc.conf
                    for _d in ${rc_directories:-/etc/rc.d}
                    do
                        if test -f "${_d}/${name}" && test -x "${_d}/${name}"
                        then
                            printf '%s/%s\n' "${_d}" "${name}"

                        fi
                    done)
                test -x "${rc_script}" || {
                    printf 'service %s could not be found' "${name}" >&2
                    exit 1
                }

                rcvar=$("${rc_script}" rcvar)
            fi

            # remove service name comment
            rcvar=${rcvar#'#'*"${NL}"}
            # only first variable (at the time of writing there can’t be more
            # than one anyway)
            rcvar=${rcvar%%"${NL}"*}
            # some (older) versions of NetBSD prefix the rcvar with $
            rcvar=${rcvar#\$}

            case ${rcvar}
            in
                (*=*)
                    # OK
                    extra=${rcvar%%=*}

                    case ${rcvar#*=}
                    in
                        ([Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1)
                            state='present' ;;
                        (*)
                            state='absent' ;;
                    esac
                    ;;
                ('')
                    # this service is not enableable
                    printf 'The service %s is not enableable\n' "${name}" >&2
                    exit 1
                    ;;
            esac
            ;;
        (openbsd)
            # OpenBSD 5.7 and higher
            if rcctl get "${name}" status >/dev/null
            then
                state='present'
            else
                state='absent'
            fi
            ;;

        (*)
            printf 'Unsupported OS: %s\n' "${os}" >&2
            exit 1
            ;;
    esac
fi

printf '%s%s\n' "${state}" "${extra:+ ${extra}}"
