#!/bin/sh -e
#
# 2016 Ander Punnar (ander at kvlt.ee)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints "0" if the package specified by --name is already installed,
# "1" otherwise.
#

if [ -f "${__object:?}/parameter/name" ]; then
    name=$(cat "${__object:?}/parameter/name")
else
    name=${__object_id:?}
fi

dpkg-query --show --showformat '${Status}' "$name" 2>/dev/null \
    | grep -Fq 'ok installed' \
    && echo 0 \
    || echo 1
