#!/bin/sh -e
#
# 2021-2022 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#


################################################################################
# Ensure svn(1) is present.

os=$(cat "${__global:?}/explorer/os")

state_should=$(cat "${__object:?}/parameter/state")

case ${os}
in
	(alpine|archlinux|gentoo|debian|devuan|ubuntu|centos|almalinux|eurolinux|rocky|fedora|scientific|suse|freebsd|openbsd)
		if test "${state_should}" != 'absent'
		then
			__package subversion
		fi
		;;
	(openwrt)
		if test "${state_should}" != 'absent'
		then
			__package subversion-client
		fi
		;;
	(*)
		: "${__type:?}"  # make shellcheck happy
		printf 'Your operating system (%s) is currently not supported by this type (%s)\n' \
			"${os}" "${__type##*/}" >&2
		printf 'Please contribute an implementation for it if you can.\n' >&2
		exit 1
		;;
esac


################################################################################
# Manage working copy root directory

case ${state_should}
in
	(present)
		:  # managed in gencode-remote
		;;
	(absent)
		# Let __directory handle removal of working copies
		__directory "/${__object_id:?}" --state absent
		;;
	(*)
		printf 'Invalid --state: %s\n' "${state_should}" >&2
		exit 1
		;;
esac
