#!/bin/sh -e
#
# 2020 Ander Punnar (ander at kvlt.ee)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Checks if the checksum of the archive on the target matches the expected
# value.
#

src="/$__object_id"

if [ -f "$__object/parameter/sum-file" ]
then
    src_sum_was_file="$( cat "$__object/parameter/sum-file" )"
else
    src_sum_was_file="$src.cdist__unpack_sum"
fi

if [ ! -f "$src" ]
then
    if [ -n "$__cdist_dry_run" ]
    then
        echo 'mismatch'
    else
        echo 'missing'
    fi
else
    if [ ! -f "$src_sum_was_file" ]
    then
        echo 'mismatch'
        exit 0
    fi

    src_sum_was="$( cat "$src_sum_was_file" )"

    src_sum_is="$( cksum "$src" | awk '{ print $1$2 }' )"

    if [ "$src_sum_was" = "$src_sum_is" ]
    then
        echo 'match'
    else
        echo 'mismatch'
    fi
fi
