#!/bin/sh -e
#
# 2016 Darko Poljak (darko.poljak at gmail.com)
# 2023 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the current state of the venv.
#
# NB: this explorer does not currently check if the directory contains a
# virtual env and if it is valid (e.g. the bin/python) link points to an existing
# Python interpreter (e.g. after a system upgrade).
#

destination="/${__object_id:?}"

if test -d "${destination}"
then
	echo present
else
	echo absent
fi
