#!/bin/sh -e
#
# 2011 Chase Allen James (nx-cdist at nu-ex.com)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

if [ -f "${__object:?}/parameter/name" ]
then
    name=$(cat "${__object:?}/parameter/name")
else
    name=${__object_id:?}
fi

state_should=$(cat "${__object:?}/parameter/state")

if grep -qF 'true' "${__object:?}/explorer/pkg_status"
then
    state_is='present'
else
    state_is='absent'
fi

[ "${state_is}" = "${state_should}" ] && exit 0

case ${state_should}
in
    (present)
        echo "gem install '${name}' --no-ri --no-rdoc"
        echo 'installed' >> "${__messages_out:?}"
        ;;
    (absent)
        echo "gem uninstall '${name}'"
        echo 'removed' >> "${__messages_out:?}"
        ;;
    (*)
        printf 'Invalid --state: %s\n' "${state_should}" >&2
        exit 1
        ;;
esac
