# NOTE: this file needs to be sourced and the $user variable needs to be defined
: "${user:?}"

prepare_cmds() { :; }

# NOTE: vixie cron, cronie, FreeBSD cron (and others?) add these "magic"
#       comments to the top of the crontab file:
#
#       # DO NOT EDIT THIS FILE - edit the master and reinstall.
#       # (/tmp/crontab.xii0AL installed on Wed Apr 13 13:04:43 2022)
#       # (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
#
#       crontab -l usually removes these lines in its output, but some
#       implementations (e.g. some versions of Cronie) don't, leading to a
#       repitition of these lines on every change.
#
#       Also, OpenBSD/NetBSD cron uses magic comments of a different form.
vixie_comment_filter='^# *\(DO NOT EDIT THIS FILE\|(.* installed on \|(\(Cron\|Cronie\) version \)'

case $(cat "${__global:?}/explorer/os")
in
	(solaris)
		crontab_print_cmd="crontab -l $(quote "${user}")"
		# TODO: On Solaris 10 crontab(1) exits with 0 if an error occurs.
		#       It only logs an error message to stderr.
		crontab_update_cmd="su - $(quote "${user}") -c crontab"

		# Make sure that awk from xpg4 is used for the scripts to work
		prepare_cmds() {
			# shellcheck disable=SC2016
			printf 'PATH=/usr/xpg4/bin/:${PATH}\n'
		}
		;;
	(*bsd)
		crontab_print_cmd="crontab -u $(quote "${user}") -l"
		crontab_update_cmd="crontab -u $(quote "${user}") -"
		;;
	(*)
		# NOTE: $!N makes sure that matching comment lines are only removed from
		#       the beginning of the file.
		crontab_print_cmd="crontab -u $(quote "${user}") -l 2>/dev/null | sed -e $(quote "/${vixie_comment_filter?}/d") -e '\$!N'"
		crontab_update_cmd="crontab -u $(quote "${user}") -"
		;;
esac


# Export variables to be used by parent script

# crontab_print_cmd:
#     prints a command which when executed prints the current state of the
#     crontab, but without automatic comments (cf. $vixie_comment_filter) if
#     necessary.
# crontab_update_cmd:
#     update the crontab from stdin

# shellcheck disable=SC2090
export crontab_print_cmd crontab_update_cmd
