#!/bin/sh -e
#
# 2020 Matthias Stecher (matthiasstecher at gmx.de)
# 2022-2023 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

# Enables/disables backports repository. Utilises __apt_source for it.

distro_codename() {
    # prefer os_release because lsb_release(1) may not be available on all installations,
    # fall back to lsb_codename if os-release is empty (old versions)
    if test -s "${__global:?}/explorer/os_release"
    then
        # NOTE: only keep the first word of the release, because (at least) Devuan
        #       adds a suffix for pre-release versions, e.g. "daedalus ceres"

        # shellcheck source=/dev/null
        (. "${__global:?}/explorer/os_release" && printf '%s\n' "${VERSION_CODENAME%% *}")
    elif test -s "${__global:?}/explorer/lsb_codename"
    then
        # shellcheck source=/dev/null
        cat "${__global:?}/explorer/lsb_codename"
    else
        return 1
    fi
}

join_lines() {
    sed -e ':a' -e '$!N' -e 's/\n/ /' -e 'ta' "$@"
}

# detect distribution
read -r os <"${__global:?}/explorer/os"
case ${os}
in
    (debian)
        mirror='http://deb.debian.org/debian/'
        dist=$(distro_codename)
        components=$(join_lines "${__object:?}/parameter/component")
        ;;
    (devuan)
        mirror='http://deb.devuan.org/merged'
        dist=$(distro_codename)
        components=$(join_lines "${__object:?}/parameter/component")
        ;;
    (ubuntu)
        mirror='http://archive.ubuntu.com/ubuntu'
        dist=$(distro_codename)
        components=$(join_lines "${__object:?}/parameter/component")
        ;;
    (*)
        : "${__type:?}"  # make shellcheck happy
        printf "Your operating system (%s) is currently not supported by this type (%s)\n" "${os}" "${__type##*/}" >&2
        printf "Please contribute an implementation for it if you can.\n" >&2
        exit 1
        ;;
esac

# error if no codename given (e.g. on Debian unstable)
test -n "${dist}" || {
    printf 'No backports for unkown version of distribution %s!\n' "${os}" >&2
    exit 1
}


# parameters
read -r state <"${__object:?}/parameter/state"

# mirror already set for the os, only override user-values
if test -f "${__object:?}/parameter/mirror"
then
    read -r mirror <"${__object:?}/parameter/mirror"
fi


# configure the backports repository
__apt_source "${dist}-backports" \
    --state "${state}" \
    --distribution "${dist}-backports" \
    --component "${components}" \
    --uri "${mirror}"
