#!/bin/sh -e
#
# 2020 Matthias Stecher (matthiasstecher at gmx.de)
# 2022 Dennis Camera (cdist at dtnr.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Enables/disables backports repository. Utilises __apt_source for it.
#


# Get the distribution codename by /etc/os-release.
#  is already executed in a subshell by string substitution
#  lsb_release may not be given in all installations
codename_os_release() {
    # shellcheck source=/dev/null
    (. "${__global:?}/explorer/os_release" && printf "%s\n" "${VERSION_CODENAME}")
}

# detect backport distribution
read -r os <"${__global:?}/explorer/os"
case ${os}
in
    (debian)
        dist=$(codename_os_release)
        components="main"
        mirror='http://deb.debian.org/debian/'
        ;;
    (devuan)
        dist=$(codename_os_release)
        components="main"
        mirror='http://deb.devuan.org/merged'
        ;;
    (ubuntu)
        dist=$(codename_os_release)
        components="main restricted universe multiverse"
        mirror='http://archive.ubuntu.com/ubuntu'
        ;;
    (*)
        : "${__type:?}"  # make shellcheck happy
        printf "Your operating system (%s) is currently not supported by this type (%s)\n" "${os}" "${__type##*/}" >&2
        printf "Please contribute an implementation for it if you can.\n" >&2
        exit 1
        ;;
esac

# error if no codename given (e.g. on Debian unstable)
test -n "${dist}" || {
    printf "No backports for unkown version of distribution %s!\n" "${os}" >&2
    exit 1
}


# parameters
read -r state <"${__object:?}/parameter/state"

# mirror already set for the os, only override user-values
if test -f "${__object:?}/parameter/mirror"
then
    read -r mirror <"${__object:?}/parameter/mirror"
fi


# configure the backports repository
__apt_source "${dist}-backports" \
    --state "${state}" \
    --distribution "${dist}-backports" \
    --component "${components}" \
    --uri "${mirror}"
