#!/bin/sh -e
#
# 2011-2013 Nico Schottelius (nico-cdist at schottelius.org)
# 2013-2022 Steven Armstrong (steven-cdist armstrong.cc)
# 2022 Dennis Camera (cdist at dtnr.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

quote() { printf '%s\n' "$*" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"; }

destination="/${__object_id:?}"
state_should=$(cat "${__object:?}/parameter/state")
stat_file="${__object:?}/explorer/stat"
fire_onchange=false

get_current_value() {
	if test -s "${stat_file}"
	then
		_name=$1
		_value=$2
		case ${_value}
		in
			([0-9]*)
				_index=2
				;;
			(*)
				_index=3
				;;
		esac
		awk "/${_name}:/ { print \$$((_index)) }" "${stat_file}"
		unset _name _value _index
	fi
}

set_group() {
	printf 'chgrp %s %s\n' "$(quote "$1")" "$(quote "${destination}")"
	printf 'chgrp %s\n' "$(quote "$1")" >>"${__messages_out:?}"
	fire_onchange=true
}

set_owner() {
	printf 'chown %s %s\n' "$(quote "$1")" "$(quote "${destination}")"
	printf 'chown %s\n' "$(quote "$1")" >>"${__messages_out:?}"
	fire_onchange=true
}

set_mode() {
	printf 'chmod %s %s\n' "$(quote "$1")" "$(quote "${destination}")"
	printf 'chmod %s\n' "$(quote "$1")" >>"${__messages_out:?}"
	fire_onchange=true
}

case ${state_should}
in
	(present|exists)
		if test -f "${__object:?}/files/upload-destination"
		then
			final_destination=${destination}
			# We change the 'global' $destination variable here so we can
			# change attributes of the new/uploaded file before moving it
			# to it's final destination.
			destination=$(cat "${__object:?}/files/upload-destination")
		fi

		# Note: Mode - needs to happen last as a chown/chgrp can alter mode by
		#  clearing S_ISUID and S_ISGID bits (see chown(2))
		for attribute in group owner mode
		do
			test -f "${__object:?}/parameter/${attribute}" || continue

			value_should=$(cat "${__object:?}/parameter/${attribute}")

			# format mode in four digits => same as stat returns
			if test "${attribute}" = 'mode' && expr "${value_should}" : '[0-9]' >/dev/null
			then
				# Convert to four-digit octal number (printf interprets
				# strings with leading 0s as octal!)
				value_should=$(printf '%04o' "0${value_should}")
			fi

			value_is=$(get_current_value "${attribute}" "${value_should}")
			if test -f "${__object:?}/files/file-uploaded" \
			|| test "${value_should}" != "${value_is}"
			then
				"set_${attribute}" "${value_should}"
			fi
		done

		if test -n "${final_destination-}"
		then
			# move uploaded file into place
			# printf 'rm -rf %s\n' "$(quote "${final_destination}")"
			printf 'mv -f %s %s\n' "$(quote "${destination}")" "$(quote "${final_destination}")"
		fi
		;;
	(pre-exists)
		;;
	(absent)
		type_is=$(cat "${__object:?}/explorer/type")
		case ${type_is}
		in
			(file|symlink)
				printf 'rm -f %s\n' "$(quote "${destination}")"
				echo remove >>"${__messages_out:?}"
				fire_onchange=true
				;;
		esac
		;;
	(*)
		printf 'Invalid --state: %s\n' "${state_should}" >&2
		exit 1
		;;
esac

if ${fire_onchange?} && test -s "${__object:?}/parameter/onchange"
then
	cat "${__object:?}/parameter/onchange"
fi
