#!/bin/sh -e
#
# 2013 Daniel Heule (hda at sfs.biz)
# 2018 Takashi Yoshi (takashi at yoshi.email)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

gentoolkit_installed="$(cat "${__object:?}/explorer/gentoolkit_installed")"
flaggie_installed="$(cat "${__object:?}/explorer/flaggie_installed")"

if [ "${gentoolkit_installed}" != "true" ]; then
    # emerge app-portage/gentoolkit
    echo "emerge app-portage/gentoolkit &> /dev/null || exit 1"
    echo "installed app-portage/gentoolkit" >> "${__messages_out:?}"
fi

if [ "${flaggie_installed}" != "true" ]; then
    # emerge app-portage/flaggie
    echo "emerge app-portage/flaggie &> /dev/null || exit 1"
    echo "installed app-portage/flaggie" >> "${__messages_out:?}"
fi
