#!/bin/sh -e
#
# 2013 Steven Armstrong (steven-cdist armstrong.cc)
# 2022 Dennis Camera (cdist at dtnr.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

destination="/${__object_id:?}"

# NOTE: check for symlink first, because if the file the symlink points to is
#       non-existent -h is true, but -e is false.
if test -h "${destination}"
then
	echo symlink
elif test ! -e "${destination}"
then
	echo none
elif test -f "${destination}"
then
	echo file
elif test -d "${destination}"
then
	echo directory
else
	echo unknown
fi
