#!/bin/sh -e
#
# 2011,2013 Nico Schottelius (nico-cdist at schottelius.org)
# 2012 Giel van Schijndel (giel plus cdist at mortis dot eu)
# 2020,2022 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

quote() { printf '%s\n' "$*" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"; }

if test -f "${__object:?}/parameter/name"
then
	name=$(cat "${__object:?}/parameter/name")
else
	name=${__object_id:?}
fi
state_should=$(cat "${__object:?}/parameter/state")
read -r state_is presence <"${__object:?}/explorer/pkg_status"

if test "${state_is}" = "${state_should}"
then
	exit 0
fi


case ${state_should}
in
	(present)
		if test "${presence}" = 'notpresent'
		then
			echo 'opkg --verbosity=0 update'
		fi

		printf 'opkg --verbosity=0 install %s\n' "$(quote "${name}")"
		echo 'installed' >>"${__messages_out:?}"
		;;
	(absent)
		printf 'opkg --verbosity=0 remove %s\n' "$(quote "${name}")"
		echo 'removed' >>"${__messages_out:?}"
		;;
	(*)
		printf 'Unknown state: %s\n' "${state_should}" >&2
		exit 1
		;;
esac
