#!/bin/sh -e
#
# 2013 contradict (contradict at gmail.com)
# 2021 Dennis Camera (dennis.camera at riiengineering.ch)
# 2021 Ander Punnar (ander at kvlt.ee)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the current group of the Git repository directory.
#

destination="/${__object_id:?}/.git"

# shellcheck disable=SC2012
group_gid=$(ls -ldn "${destination}" | awk '{ print $4 }')

# NOTE: +1 because $((notanum)) prints 0.
if test $((group_gid + 1)) -ge 0
then
	group_should=$(cat "${__object:?}/parameter/group")

	if expr "${group_should}" : '[0-9]*$' >/dev/null
	then
		printf '%u\n' "${group_gid}"
	else
		if command -v getent >/dev/null 2>&1
		then
			getent group "${group_gid}" | cut -d : -f 1
		else
			awk -F: -v gid="${group_gid}" '$3 == gid { print $1 }' /etc/group
		fi
	fi
fi
