#!/bin/sh -e
#
# 2013 contradict (contradict at gmail.com)
# 2021 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the current owner of the Git repository directory.
#

destination="/${__object_id:?}/.git"

# shellcheck disable=SC2012
owner_uid=$(ls -ldn "${destination}" | awk '{ print $3 }')

# NOTE: +1 because $((notanum)) prints 0.
if test $((owner_uid + 1)) -ge 0
then
	owner_should=$(cat "${__object:?}/parameter/owner")

	if expr "${owner_should}" : '[0-9]*$' >/dev/null
	then
		printf '%u\n' "${owner_uid}"
	else
		printf '%s\n' "$(id -u -n "${owner_uid}")"
	fi
fi
