#!/bin/sh -e
#
# 2021 Ander Punnar (ander at kvlt.ee)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints whether the APT cache is outdated.
#

maxage=$(cat "${__object:?}/parameter/maxage")

# Some of following code is duplicated in __package_apt/gencode-remote.
# If you change anything here, please make changes there too.
if [ ! -d /var/lib/apt/lists ] \
    || [ -n "$(find /etc/apt -newer /var/lib/apt/lists)" ] \
    || [ ! -f /var/cache/apt/pkgcache.bin ] \
    || [ "$(stat --format %Y /var/cache/apt/pkgcache.bin)" -lt "$(date +%s -d "-${maxage} seconds")" ]
then
    echo 'outdated'
else
    echo 'current'
fi
