#!/bin/sh -e
#
# 2019 Nico Schottelius (nico-cdist at schottelius.org)
# 2020,2022 Dennis Camera (skonfig at dtnr.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

case $(cat "${__global}/explorer/os")
in
	(alpine)
		__package shadow
		;;
	(openwrt)
		case $(cat "${__object}/parameter/state")
		in
			(present)
				if test -f "${__object:?}/parameter/create-home"
				then
					# NOTE: OpenWrt does not have /home by default.
					#       __user --create-home would thus error:
					#
					#       useradd: cannot create directory /home/user
					__directory /home --owner 0 --group 0 --mode 0755
				fi
				if test -s "${__object}/explorer/passwd"
				then
					# NOTE: The package might not be required if no changes
					# are required, but determining if changes are required is
					# out of scope here, and 40k should be okay, I hope.
					__package shadow-usermod
				else
					__package shadow-useradd
				fi
				;;
			(absent)
				if test -s "${__object}/explorer/passwd"
				then
					__package shadow-userdel
				fi
				;;
		esac
		;;
	(*)
		:
		;;
esac
