#!/bin/sh -e
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
# 2014 og (niko at ghetto.sh)
# 2015 Jonathan A. Kollasch (jakllsch at kollasch.net)
# 2017 Philippe Grégoire (pg at pgregoire.xyz)
# 2019-2020,2024-2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Get an existing user's shadow entry.
#

name=${__object_id:?}

os=$("${__explorer:?}/os")
case ${os}
in
	(freebsd|netbsd)
		database='passwd'
		;;
	(openbsd)
		database='master.passwd'
		;;
	(*)
		# default to using shadow passwords
		database='shadow'
		;;
esac

if command -v getent >/dev/null 2>&1
then
	# shellcheck disable=SC2015
	getent "${database}" "${name}" 2>/dev/null && exit || :  # fallback to file
fi
if test -n "${database}" && test -s "/etc/${database}"
then
	awk -v name="${name}" -F: '$1==name' "/etc/${database}"
fi
