#!/bin/sh -e
#
# 2020 Ander Punnar (ander at kvlt.ee)
# 2022 Travis Paul (tr at vispaul.me)
# 2023 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat "${__global:?}/explorer/os")

src="/${__object_id:?}"

case ${src}
in
    (*.7z)
        __package p7zip
        ;;
    (*.bz2|*.tbz2)
        case ${os}
        in
            (freebsd)
                # bzip2 is part of freebsd base system
                ;;
            (*)
                __package bzip2
                ;;
        esac
        ;;
    (*.lzma|*.xz|*.txz)
        case ${os}
        in
            (debian|ubuntu|devuan)
                __package xz-utils
                ;;
            (alpine|centos|almalinux|eurolinux|rocky)
                __package xz
                ;;
        esac
        ;;
    (*.rar)
        case ${os}
        in
            (debian|ubuntu|devuan|alpine|freebsd)
                __package unrar
                ;;
        esac
        ;;
    (*.zip)
        __package unzip
        ;;
esac
