#!/bin/sh -e
#
# 2017 Ľubomír Kučera (lubomir.kucera.jr at gmail.com)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

systemctl_present=$(cat "${__object:?}/explorer/systemctl-present")

if [ "${systemctl_present}" -ne 0 ]
then
    echo 'systemctl does not seem to be present on this system' >&2

    exit 1
fi

name=${__object_id:?}
source=$(cat "${__object:?}/parameter/source")
state=$(cat "${__object:?}/parameter/state")
enablement_state=$(cat "${__object:?}/parameter/enablement-state")

# The unit must be disabled before removing its unit file. The unit file is
# therefore removed by gencode-remote of this type, not here.
if [ -z "${source}" ] || [ "${state}" = 'absent' ]
then
    exit 0
fi

# stdin is not propagated automatically to sub-objects
if [ "${source}" = '-' ]
then
    source="${__object:?}/stdin"
fi

unitfile_state=${state}
if [ "${enablement_state}" = 'masked' ]
then
    # Masking creates a symlink from /etc/systemd/system/<unit> to /dev/null.
    # This process fails with "Failed to execute operation: Invalid argument"
    # if file /etc/systemd/system/<unit> already exists. We must therefore
    # remove it.
    unitfile_state='absent'
fi

unitfile_dir='/etc/systemd/system'

if [ -f "${__object:?}/parameter/drop-in" ] \
    || [ -f "${__object:?}/parameter/unique-drop-in" ]
then
    unitfile_dir="${unitfile_dir}/${name}.d"

    __directory "${unitfile_dir}" \
        --owner root \
        --group root \
        --mode 755

    # This is legacy.
    cdist_dropin="${unitfile_dir}/cdist.conf"

    __file "${cdist_dropin}" \
        --state absent

    export require="__directory/${unitfile_dir} __file${cdist_dropin}"

    # Equally named drop-in files further down the prefix hierarchy override those further up:
    # https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html
    # Assumption: If you have systemd, then you have md5sum.
    unique_dropin="${unitfile_dir}/skonfig-$(echo "${name}" | md5sum | awk '{print $1}').conf"

    # This is default name for drop-in if you run `systemctl edit <unit>`.
    default_dropin="${unitfile_dir}/override.conf"

    if [ -f "${__object:?}/parameter/unique-drop-in" ]
    then
        unitfile="${unique_dropin}"

        __file "${default_dropin}" \
            --state absent

        export require="__file${default_dropin}"
    else
        unitfile="${default_dropin}"

        __file "${unique_dropin}" \
            --state absent

        export require="__file${unique_dropin}"
    fi
else
    unitfile="${unitfile_dir}/${name}"
fi

__file "${unitfile}" \
    --mode 644 \
    --onchange 'systemctl daemon-reload' \
    --source "${source}" \
    --state "${unitfile_state}"
