#!/bin/sh -e
#
# 2019 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the maximum length of a host name if defined on the system.
#

command -v getconf >/dev/null || exit 0

val=$(getconf HOST_NAME_MAX 2>/dev/null) || exit 0

if test -n "${val}" -a "${val}" != 'undefined'
then
	echo "${val}"
fi
