#!/bin/sh
#
# 2014 Daniel Heule (hda at sfs.biz)
# 2014 Thomas Oettli (otho at sfs.biz)
# 2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the number of CPU sockets in use on the target.
#

os=$("${__explorer:?}/os")
case ${os}
in
    (macosx)
        system_profiler SPHardwareDataType | grep -F 'Number of Processors' | awk -F': ' '{print $2}'
        ;;
    (*)
        if test -r /proc/cpuinfo
        then
            sockets=$(grep -e '^physical id[[:blank:]]*:' /proc/cpuinfo | sort -u | wc -l)
            if test $((sockets)) -lt 1
            then
                sockets=$(grep -c -e '^processor[[:blank:]]*:' /proc/cpuinfo)
            fi
            echo $((sockets))
        fi
        ;;
esac
