#!/bin/sh
#
# 2014 Daniel Heule (hda at sfs.biz)
# 2014 Thomas Oettli (otho at sfs.biz)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the number of CPU cores available on the target.
# Note that this number includes virtual SMT threads.
#

os=$("${__explorer:?}/os")
case ${os}
in
    (macosx)
        sysctl -n hw.physicalcpu
        ;;
    (openbsd)
        sysctl -n hw.ncpuonline
        ;;
    (freebsd|netbsd)
        PATH=$(getconf PATH)
        sysctl -n hw.ncpu
        ;;
    (*)
        if test -r /proc/cpuinfo
        then
            cores=$(grep -c -e '^processor[[:blank:]]*:' /proc/cpuinfo)
            test $((cores)) -ge 1 && echo $((cores)) || echo 1
        fi
        ;;
esac
