#!/bin/sh
#
# 2014 Daniel Heule (hda at sfs.biz)
# 2014 Thomas Oettli (otho at sfs.biz)
# 2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the number of CPU cores available on the target.
# Note that this number includes virtual SMT threads.
#

os=$("${__explorer:?}/os")
case ${os}
in
    (beos)
        sysinfo -cpu | grep -c '^CPU #[0-9][0-9]*'
        ;;
    (haiku)
        nproc
        ;;
    (macosx)
        sysctl -n hw.physicalcpu
        ;;
    (netbsd|openbsd)
        # OpenBSD sysctl(8) always exits 0 (thus `grep .' to check for success)
        /sbin/sysctl -n hw.ncpuonline 2>/dev/null | grep . \
        || /sbin/sysctl -n hw.ncpu
        ;;
    (freebsd)
        sysctl -n hw.ncpu
        ;;
    (*)
        if test -r /proc/cpuinfo
        then
            cores=$(grep -c -e '^processor[[:blank:]]*:' /proc/cpuinfo || :)
            test $((cores)) -gt 0 || cores=1
            printf '%u\n' "${cores}"
        fi
        ;;
esac
