#!/bin/sh -e
#
# based on previous work by other people, modified by:
# 2020,2022-2023 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Finds disks of the system (excl. RAM disks, floppy, CDROM).
#

uname_s=$(uname -s)

case ${uname_s}
in
    FreeBSD)
        sysctl -n kern.disks
    ;;
    OpenBSD)
        sysctl -n hw.disknames | grep -Eo '[lsw]d[0-9]+'
    ;;
    NetBSD)
        PATH=$(getconf PATH)
        sysctl -n hw.disknames | awk -v RS=' ' '/^[lsw]d[0-9]+/'
    ;;
    Darwin)
        diskutil list \
        | awk '
          /^\/dev\// {
              if (match($0, /\(.*\):$/)) {
                  NA = split(substr($0, RSTART + 1, RLENGTH - 3), attrs, ", *")
                  for (i = 1; i <= NA; i++)
                      if (attrs[i] == "synthesized")
                          next
              }
              sub(/^\/dev\//, "", $1)
              print $1
          }'
    ;;
    Linux)
        # list of major device numbers toexclude:
        #  ram disks, floppies, cdroms
        # https://www.kernel.org/doc/Documentation/admin-guide/devices.txt
        ign_majors='1 2 11'

        if command -v lsblk >/dev/null 2>&1
        then
            lsblk -e "$(echo "${ign_majors}" | tr ' ' ',')" -dno name
        elif test -d /sys/block/
        then
            # shellcheck disable=SC2012
            ls -1 /sys/block/ \
            | awk -v ign_majors="$(echo "${ign_majors}" | tr ' ' '|')" '
                {
                  devfile = "/sys/block/" $0 "/dev"
                  getline devno < devfile
                  close(devfile)
                  if (devno !~ "^(" ign_majors "):") print
                }'
        else
            echo "Don't know how to list disks on Linux without lsblk and sysfs." >&2
            echo 'If you can, please submit a patch.'>&2
        fi
    ;;
    SunOS)
        # NOTE: format(1m) - disk partitioning and maintenance utility.
        #       When called with no arguments, it will print a list of disks it
        #       can find and prompt the user to select one.
        #       passing in /dev/null as stdin will cancel the disk selection.
        format </dev/null \
        | sed -n \
              -e '1,/^AVAILABLE DISK/d' \
              -e 's/^ *[0-9]\{1,\}\. //p' \
        | cut -d ' ' -f 1
    ;;
    *)
        printf "Don't know how to list disks for %s operating system.\n" "${uname_s}" >&2
        printf 'If you can please submit a patch\n' >&2
    ;;
esac \
| xargs
