#!/bin/sh -e
#
# 2019 Ander Punnar (ander at kvlt.ee)
# 2019,2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Lists all network interfaces available on the target.
# One interface name per line.
# Output is sorted lexicographically.
#

if command -v ip >/dev/null 2>&1
then
	ip -o link show | sed -n 's/^[0-9]\+: \(.\+\): <.*/\1/p'
elif command -v ifconfig >/dev/null 2>&1
then
	os=$("${__explorer:?}/os")
	case ${os}
	in
		(beos|haiku)
			ifconfig \
			| sed -n -e 's/^\([^[:blank:]]\{1,\}\)\([[:blank:]]*Hardware type:.*\)\{0,1\}$/\1/p'
			;;
		(*)
			ifconfig -a | sed -n \
				-e 's/^\([^[:blank:]]*\):[[:blank:]]*flags=.*$/\1/p' \
				-e 's/^\([^[:blank:]]*\)[[:blank:]]*Link encap.*$/\1/p'
			;;
	esac
fi \
| LC_ALL=C sort -u
