#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the LSB ID.
#

set +e
case "$("$__explorer/os")" in
   checkpoint)
       echo "CheckPoint"
   ;;
   openwrt)
      # shellcheck disable=SC1091
      (. /etc/openwrt_release && echo "$DISTRIB_ID")
   ;;
   *)
      lsb_release=$(command -v lsb_release)
      if [ -x "$lsb_release" ]; then
         $lsb_release --short --id
      fi
   ;;
esac
