#!/bin/sh -e
#
# 2014 Daniel Heule (hda at sfs.biz)
# 2014 Thomas Oettli (otho at sfs.biz)
# 2017 Philippe Gregoire (pg at pgregoire.xyz)
# 2020-2021,2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the amount of memory physically installed in the system, or if that
# cannot be determined the amount available to the operating system kernel,
# in kibibytes (kiB).
#

str2bytes() {
	awk -F' ' '
	$2 ==   "B" || !$2 { print $1 }
	$2 ==  "kB" { printf "%.f\n", ($1 * 1000) }
	$2 ==  "MB" { printf "%.f\n", ($1 * 1000 * 1000) }
	$2 ==  "GB" { printf "%.f\n", ($1 * 1000 * 1000 * 1000) }
	$2 ==  "TB" { printf "%.f\n", ($1 * 1000 * 1000 * 1000 * 1000) }
	$2 == "kiB" { printf "%.f\n", ($1 * 1024) }
	$2 == "MiB" { printf "%.f\n", ($1 * 1024 * 1024) }
	$2 == "GiB" { printf "%.f\n", ($1 * 1024 * 1024 * 1024) }
	$2 == "TiB" { printf "%.f\n", ($1 * 1024 * 1024 * 1024 * 1024) }'
}

bytes2kib() {
	awk '$0 > 0 { printf "%.f\n", ($0 / 1024) }'
}


case $(uname -s)
in
	(BeOS|Haiku)
		bytes=$(sysinfo -mem | sed -n -e 's#^.*(used/max *\([0-9]*\) */ *\([0-9]*\))$#\2#p')
		awk -v bytes="${bytes}" '
		BEGIN {
			if (0 > bytes) {
				# whoops, signed 32-bit integer overflow...
				bytes = (2**32 + bytes)
			}
			printf "%.f\n", (bytes / 1024)
		}'
		;;
	(Darwin)
		sysctl -n hw.memsize | bytes2kib
		;;
	(FreeBSD)
		sysctl -n hw.realmem | bytes2kib
		;;
	(NetBSD)
		# NOTE: This reports "usable" memory, not physically installed memory
		#       (on some architectures).
		#
		#       hw.physmem64 is available on NetBSD >= 2.0
		/sbin/sysctl -n hw.physmem64 | bytes2kib
		;;
	(OpenBSD)
		# NOTE: This reports "usable" memory, not physically installed memory
		#       (on some architectures).
		sysctl -n hw.physmem | bytes2kib
		;;
	(SunOS)
		# Make sure that awk from xpg4 is used for the scripts to work
		export PATH="/usr/xpg4/bin:${PATH}"
		prtconf \
		| awk -F ': ' '
		  $1 == "Memory size" { sub(/Megabytes/, "MiB", $2); print $2 }
		  /^$/ { exit }' \
		| str2bytes \
		| bytes2kib
		;;
	(Linux)
		if test -d /sys/devices/system/memory
		then
			# Use memory blocks if the architecture (e.g. x86, PPC64, s390)
			# supports them (they denote physical memory)
			if num_mem_blocks=$(cat /sys/devices/system/memory/memory[0-9]*/state 2>/dev/null | grep -cxF online)
			then
				mem_block_size=$(cat /sys/devices/system/memory/block_size_bytes)
				echo $((num_mem_blocks * 0x${mem_block_size})) | bytes2kib
				exit 0
			fi
		fi
		if test -r /proc/meminfo
		then
			# Fall back to meminfo file on other architectures (e.g. ARM, MIPS,
			# PowerPC)
			# NOTE: This is "usable" memory, not physically installed memory.
			awk -F ': +' '$1 == "MemTotal" { sub(/B$/, "iB", $2); print $2 }' /proc/meminfo \
			| str2bytes \
			| bytes2kib
		fi
		;;
	(*)
		printf "Your kernel (%s) is currently not supported by the memory explorer\n" "$(uname -s)" >&2
		printf "Please contribute an implementation for it if you can.\n" >&2
		exit 1
		;;
esac
