#!/bin/sh -e
#
# 2022 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Checks if --user is allowed to use cron.
#

cron_ok() { echo true; exit 0; }
cron_fail() { printf '%s\n' "$1" >&2; exit "$2"; }

user=$(cat "${__object:?}/parameter/user")

case $(uname -s)
in
	(SunOS)
		msg=$(LC_ALL=C crontab -l "${user}" 2>&1 >/dev/null) || {
			err=$?
			case ${msg}
			in
				(*'not allowed to execute cronjobs'*)
					# test for this message specifically beacuse on
					# Solaris 11.x "can't open your crontab file" will
					# also be printed.
					cron_fail "${msg}" ${err} ;;
				(*"can't open your crontab file.")
					cron_ok ;;
				(*)
					cron_fail "${msg}" ${err} ;;
			esac
		}
		;;
	(*)
		msg=$(LC_ALL=C crontab -u "${user}" -l 2>&1 >/dev/null) || {
			err=$?
			case ${msg}
			in
				(*'no crontab for '*)
					cron_ok ;;
				("crontab: can't open "*[Nn]'o such file or directory')
					# BusyBox
					cron_ok ;;
				(*)
					cron_fail "${msg}" ${err} ;;
			esac
		}
		;;
esac
