#!/bin/sh -e
#
# 2022 Dennis Camera (cdist at dtnr.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

name=${__object_name:?}
user=$(cat "${__object:?}/parameter/user")

crontab_list() {
	case $(uname -s)
	in
		(SunOS)
			crontab -l "${user}" 2>/dev/null ;;
		(*)
			crontab -u "${user}" -l 2>/dev/null ;;
	esac
}

grep_suffix() {
	awk -v suffix="$1" 'substr($0, length($0) - length(suffix) + 1) == suffix'
}

crontab_list | grep_suffix " # ${name}"
