#!/bin/sh -e
#
# 2024 Ander Punnar (ander-at-kvlt-dot-ee)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.

if [ -f "$__object/parameter/path" ]
then
    path="$( cat "$__object/parameter/path" )"
else
    path="/$__object_id"
fi

if [ ! -d "$path" ]
then
    exit 0
fi

# deprecated
if [ -f "$__object/parameter/pattern" ] || [ -f "$__object/parameter/exclude" ]
then
    set -- '-maxdepth' 1 "$@"

    if [ -f "$__object/parameter/pattern" ]
    then
        cp "$__object/parameter/pattern" "$__object/parameter/rm-regex"
    fi

    if [ -f "$__object/parameter/exclude" ]
    then
        cp "$__object/parameter/exclude" "$__object/parameter/not-regex"
    fi
fi
# /deprecated

if [ -f "$__object/parameter/rm-name" ]
then
    while read -r rm_name
    do
        set -- '-name' "$rm_name" "$@"
    done \
        < "$__object/parameter/rm-name"
fi

if [ -f "$__object/parameter/rm-path" ]
then
    while read -r rm_path
    do
        set -- '-path' "$rm_path" "$@"
    done \
        < "$__object/parameter/rm-path"
fi

if [ -f "$__object/parameter/rm-regex" ]
then
    while read -r rm_regex
    do
        set -- '-regex' "$rm_regex" "$@"
    done \
        < "$__object/parameter/rm-regex"
fi

if [ -f "$__object/parameter/not-name" ]
then
    while read -r not_name
    do
        set -- '!' '-name' "$not_name" "$@"
    done \
        < "$__object/parameter/not-name"
fi

if [ -f "$__object/parameter/not-path" ]
then
    while read -r not_path
    do
        set -- '!' '-path' "$not_path" "$@"
    done \
        < "$__object/parameter/not-path"
fi

if [ -f "$__object/parameter/not-regex" ]
then
    while read -r not_regex
    do
        set -- '!' '-regex' "$not_regex" "$@"
    done \
        < "$__object/parameter/not-regex"
fi

set -- 'find' "$path" '!' '-path' "$path" "$@"

# for debugging purposes
#echo "__clean_path/$__object_id: $*" >&2

"$@"
