#!/bin/sh -e
#
# 2024 Ander Punnar (ander at kvlt.ee)
# 2024 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints all files found which should be removed.
#

if [ -f "${__object:?}/parameter/path" ]
then
    path=$(cat "${__object:?}/parameter/path")
else
    path="/${__object_id:?}"
fi

if [ ! -d "$path" ]
then
    exit 0
fi

# deprecated
if [ -f "${__object:?}/parameter/pattern" ] || [ -f "${__object:?}/parameter/exclude" ]
then
    set -- '-maxdepth' 1 "$@"

    if [ -f "${__object:?}/parameter/pattern" ]
    then
        cp "${__object:?}/parameter/pattern" "${__object:?}/parameter/rm-regex"
    fi

    if [ -f "${__object:?}/parameter/exclude" ]
    then
        cp "${__object:?}/parameter/exclude" "${__object:?}/parameter/not-regex"
    fi
fi
# /deprecated

for _p in "${__object:?}"/parameter/*
do
    test -s "${_p}" || continue
    case ${_p##*/}
    in
        (rm-*)
            while read -r _v
            do
                set -- "-${_p##*/rm-}" "${_v}" "$@"
            done <"${_p}"
            ;;
        (not-*)
            while read -r _v
            do
                set -- '!' "-${_p##*/not-}" "${_v}" "$@"
            done <"${_p}"
            ;;
    esac
done


set -- 'find' "$path" '!' '-path' "$path" "$@"

# for debugging purposes
#echo "__clean_path/${__object_id:?}: $*" >&2

"$@"
