#!/bin/sh
#
# 2014 Steven Armstrong (steven-cdist at armstrong.cc)
# 2019 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the path of the destination file chosen to be managed.
#

if [ -f "${__object:?}/parameter/file" ]
then
	cat "${__object:?}/parameter/file"
else
	if [ -s "${__object:?}/parameter/owner" ]
	then
		owner=$(cat "${__object:?}/parameter/owner")
	else
		owner=${__object_id:?}
	fi

	if command -v getent >/dev/null
	then
		owner_line=$(getent passwd "${owner}")
	elif [ -f /etc/passwd ]
	then
		case ${owner}
		in
			[0-9][0-9]*)
				owner_line=$(awk -F: "\$3 == \"${owner}\" { print }" /etc/passwd)
				;;
			*)
				owner_line=$(awk -F: "\$1 == \"${owner}\" { print }" /etc/passwd)
				;;
		esac
	fi

	if [ -n "${owner_line}" ]
	then
		home=$(echo "${owner_line}" | cut -d':' -f6)
	fi

	if [ ! -d "${home}" ]
	then
		# Don't know how to determine user's home directory, fall back to ~
		home="~${owner}"
		command -v realpath >/dev/null && home=$(realpath "${home}")
	fi

	[ -d "${home}" ] && echo "${home}/.ssh/authorized_keys"
fi
