#!/bin/sh -e
#
# 2020 Ander Punnar (ander at kvlt.ee)
# 2020 Darko Poljak (foss at ungleich.com)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

# shellcheck disable=SC1090
# shellcheck disable=SC1091
file="$( . "$__type_explorer/file" )"

if [ -f "$file" ]
then
    cat "$file"
fi
