#!/bin/sh
#
# 2013 Steven Armstrong (steven-cdist armstrong.cc)
# 2023 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Print the current state of the destination file.
#

destination="/${__object_id:?}"

# NOTE: Test for symlink first because a symlink can exist but point to a
#       non-existing file, in which case `test -h` is 0 but `test -e` is 1.
if [ -h "${destination}" ]
then
    echo symlink
elif [ ! -e "${destination}" ]
then
    echo none
elif [ -f "${destination}" ]
then
    type=$(cat "${__object:?}/parameter/type")
    case ${type}
    in
        hard)
            # Currently not worth the effor to change it, stat is not defined by POSIX
            # and different OSes has different implementations for it.
            # shellcheck disable=SC2012
            link_count=$(ls -l "${destination}" | awk '{ print $2 }')
            if [ "${link_count}" -gt 1 ]
            then
                echo hardlink
                exit 0
            fi
        ;;
    esac
    echo file
elif [ -d "${destination}" ]
then
    echo directory
else
    echo unknown
fi
