#!/bin/sh -e
#
# 2021-2022 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the group of the current working copy root (if present).
# The printed value will be
#  the GID if --group is a number (or not set)
#  the name if --group is not a number
#
#  nothing if the working copy does not exist
#

destination="/${__object_id:?}/.svn"

test -d "${destination}" || exit 0

# shellcheck disable=SC2012
group_gid=$(ls -ldn "${destination}" | awk '{ print $4 }')

# NOTE: +1 because $((notanum)) prints 0.
if test $((group_gid + 1)) -ge 0
then
	group_should=$(cat "${__object:?}/parameter/group" 2>/dev/null || true)

	if expr "${group_should}" : '[0-9]*$' >/dev/null
	then
		printf '%u\n' "${group_gid}"
	else
		if command -v getent >/dev/null 2>&1
		then
			getent group "${group_gid}" | cut -d ':' -f 1
		else
			awk -F: -v gid="${group_gid}" '$3 == gid { print $1 }' /etc/group
		fi
	fi
fi
