#!/bin/sh -e
#
# 2021 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the mode of the current working copy root (if present).
#

destination="/${__object_id:?}/.svn"

test -d "${destination}" || exit 0

# shellcheck disable=SC2012
ls -ldn "${destination}" \
| awk '{
	m = substr($0, 1, 10)
	for (i = 8; i >= 0; --i) {
		c = substr(m, 10-i, 1)
		k += ((c~/[rwxst]/)*2^i)
		if ((i % 3) == 0)
			k += (tolower(c)~/[lst]/)*2^(9+i/3)
	}
	printf("%04o", k)
  }'
