#!/bin/sh -e
#
# 2021-2022 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the owner of the current working copy root (if present).
# The printed value will be
#  the UID if --owner is a number (or not set)
#  the name if --owner is not a number
#
#  nothing if the working copy does not exist
#

destination="/${__object_id:?}/.svn"

test -d "${destination}" || exit 0

# shellcheck disable=SC2012
owner_uid=$(ls -ldn "${destination}" | awk '{ print $3 }')

# NOTE: +1 because $((notanum)) prints 0.
if test $((owner_uid + 1)) -ge 0
then
	owner_should=$(cat "${__object:?}/parameter/owner" 2>/dev/null || true)

	if expr "${owner_should}" : '[0-9]*$' >/dev/null
	then
		printf '%u\n' "${owner_uid}"
	else
		printf '%s\n' "$(id -u -n "${owner_uid}")"
	fi
fi
