#!/bin/sh -e
#
# 2022 Dennis Camera (cdist at dtnr.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

quote() { printf '%s\n' "$*" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"; }

state_is=$(cat "${__object:?}/explorer/state")
state_should=$(cat "${__object:?}/parameter/state")

# short circuit if state is the same and no further extras to install
test "${state_is}" != "${state_should}" || exit 0

requirement=$(cat "${__object:?}/explorer/requirement")

pip=$(cat "${__object:?}/explorer/pip")
test -n "${pip}" || {
	echo 'Could not find pip.' >&2
	echo 'Please make sure that pip is installed or specify the command to use in --pip.' >&2
	exit 1
}

runas=$(cat "${__object:?}/parameter/runas" 2>/dev/null || :)

do_cmd() {
	if test -n "${runas}"
	then
		printf 'su -l %s -c %s\n' "$(quote "${runas}")" "$(quote "$1")"
	else
		printf '%s\n' "$1"
	fi
}

case ${state_should}
in
	(present)
		do_cmd "${pip} install -q $(quote "${requirement}")"
		echo installed >> "${__messages_out:?}"
		;;
	(absent)
		do_cmd "${pip} uninstall -q -y $(quote "${requirement}")"
		echo removed >> "${__messages_out:?}"
		;;
	(*)
		printf 'Invalid --state: %s\n' "${state_should}" >&2
		exit 1
		;;
esac
